version: '3.8'
services:
  api:
    build: .
    volumes:
      - .:/app
      - upload_volume:/api/uploads
    ports:
      - "${API_PORT}:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./db/init:/docker-entrypoint-initdb.d
      - db_volume:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
volumes:
  upload_volume:
  db_volume:
